apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: illuminati-backend-prod
  namespace: argocd

spec:
  destination:
    namespace: app-namespace
    server: https://kubernetes.default.svc

  source:
    path: backend
    repoURL: https://github.com/Red-I3ull/backend-illuminati-helm-argo.git
    targetRevision: BULL-51-create-repo-for-backend-and-application-for-argocd-and-deploy-back
    helm:
      valueFiles:
        - values-prod.yaml

  project: illuminati-project

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true